version: '3'
services:
  auth:
    image: ghcr.io/${GITHUB_REPOSITORY}/auth:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env

  reservation:
    image: ghcr.io/${GITHUB_REPOSITORY}/reservation:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
    env_file:
      - .env

  payment:
    image: ghcr.io/${GITHUB_REPOSITORY}/payment:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
    env_file:
      - .env

  notifications:
    image: ghcr.io/${GITHUB_REPOSITORY}/notifications:${VERSION:-latest}
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
    env_file:
      - .env