services:
  database:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    container_name: reservation_app_database

  reservations:
    build: 
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: "npm run start:dev reservation"
    ports:
      - "3000:3000"
    restart: always
    container_name: reservation_service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database

  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: "npm run start:dev auth"
    ports:
      - "3001:3001"
    restart: always
    container_name: auth_service
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
    
    
    