name: Build and Push Production Docker Images

on: 
  workflow_dispatch:
    inputs:
      versionType:
        type: choice
        description: Select the version to bump (default is 'patch')
        options: 
        - major
        - minor
        - patch

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set version tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Auth service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/auth/Dockerfile
          push: true
          tags: |
            username/auth::${{ github.event.inputs.version }}
            username/auth:latest

      - name: Build and push Reservation service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/reservation/Dockerfile
          push: true
          tags: |
            username/reservation:${{ github.event.inputs.version }}
            username/reservation:latest

      - name: Build and push Payment service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/payment/Dockerfile
          push: true
          tags: |
            username/payment:${{ github.event.inputs.version }}
            username/payment:latest

      - name: Build and push Notifications service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/notifications/Dockerfile
          push: true
          tags: |
            username/notifications:${{ github.event.inputs.version }}
            username/notifications:latest

      - name: Create Release Summary
        if: github.event_name == 'release'
        run: |
          echo "## Docker Images" >> $GITHUB_STEP_SUMMARY
          echo "The following images have been built and pushed:" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/auth:${{ github.event.inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/reservation:${{ github.event.inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/payment:${{ github.event.inputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/notifications:${{ github.event.inputs.version }}\`" >> $GITHUB_STEP_SUMMARY

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Mock deployment
        run: |
          echo "Mocking deployment of Auth Service..."
          echo "Mocking deployment of Reservation Service..."
          echo "Mocking deployment of Payment Service..."
          echo "Mocking deployment of Notifications Service..."
          
      - name: Mock deployment verification
        run: |
          echo "Mock Deployment Status:"
          echo "auth-deployment          1/1     Running   0          1m"
          echo "reservation-deployment   1/1     Running   0          1m"
          echo "payment-deployment       1/1     Running   0          1m"
          echo "notifications-deployment 1/1     Running   0          1m"
