name: CI/CD for NestJS Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Adjust to the version you're using

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint # Make sure 'lint' script is defined in your package.json

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Adjust to the version you're using

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test # Ensure the 'test' script is defined in your package.json
