name: CI/CD for NestJS Microservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Adjust to the version you're using

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint # Make sure 'lint' script is defined in your package.json

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7 # Adjust to the version you're using

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test # Ensure the 'test' script is defined in your package.json

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Auth service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/auth/Dockerfile
          push: false
          load: true
          tags: auth:test

      - name: Build Reservation service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/reservation/Dockerfile
          push: false
          load: true
          tags: reservation:test

      - name: Build Payment service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/payment/Dockerfile
          push: false
          load: true
          tags: payment:test

      - name: Build Notifications service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/notifications/Dockerfile
          push: false
          load: true
          tags: notifications:test

